### PR TITLE
Added markdown support for endpoint docstrings

### PR DESCRIPTION
**Pull request by mikeengland**
I recently started using drfdocs and wanted to add some documentation onto each view I have. Some extra documentation I have needed to be formatted (line breaks etc) and was longer than a single line.

This simple change allows reStructuredText to be added to a DRF View docstring, meaning users can add structured documentation that can be viewed when clicking on each API on the docs page.

### CODE REVIEW

**Comment by rainyday** [comment]
Markdown support would be more useful here since it is already used in DRF's html views for docstrings.

**Comment by mikeengland** [comment]
If markdown would be more useful for this project it would be very easy to implement. I'll look at changing it in this pull request.

**Comment by Dean-Christian-Armada** [comment]
Is markdown enabled already?

**Comment by rainyday** [comment]
@Dean-Christian-Armada It's an optional feature of DRF that requires the markdown package to be installed. See: http://www.django-rest-framework.org/topics/documenting-your-api/#self-describing-apis

**Comment by Dean-Christian-Armada** [comment]
@rainyday I already installed markdown using pip, in fact it works when I use plain DRF but not with Django Rest Framework. Take a look at the pictures

selection_085

selection_086

selection_087

**Comment by mikeengland** [comment]
@Dean-Christian-Armada I guess you mean markdown works using the DRF browsable API but not in DRFDocs right now?

**Comment by Dean-Christian-Armada** [comment]
@mikeengland , Exactly!

**Comment by Dean-Christian-Armada** [comment]
@mikeengland , You are exactly right! Is it supposed to behave that way?

**Comment by mikeengland** [comment]
I believe so. I didn't get any markdown support on doc strings in DRFDocs until I added this commit.

**Comment by Dean-Christian-Armada** [comment]
@mikeengland , oh ok,, but it will definitely be helpful if the markdown is implemented the same as the browsable API....

**Comment by slav0nic** [comment]
i think drfdocs should use function from drf.views `get_view_description(view_cls, html=True)` (what drf does)  instead `inspect.doc`

**Comment by StyXman** [comment]
@mikeengland : Could you please update you branch? I plan to merge thi soon.

**Comment by mikeengland** [comment]
Hey @StyXman, is this still needed now that https://github.com/manosim/django-rest-framework-docs/pull/127 is merged?

**Comment by StyXman** [comment]
@mikeengland : probably not, but I'll take some things from your change and try to properly give you credit. Otherwise we could go through another PR so it's more 'official' (you get you stats, etc). As you wish.

**Pull request closed without merging**
