### PR TITLE
Create setup.cfg

### PR DESCRIPTION
**Pull request by JensTimmerman**
when updating rpm's from django-rest-framework-docs to drfdocs the rpm fails to update because of conflicting files, this obsolets should tell yum/dnf to first remove the old rpm

### CODE REVIEW

**Comment by StyXman** [comment]
@JensTimmerman Could you please update your branch? I plan to merge it.

**Comment by JensTimmerman** [comment]
@StyXman done, I just had to click the 'update branch' button here.

**Comment by StyXman** [comment]
@JensTimmerman : who uses this rpm spec file? is this part of an official distribution, or people use it internally?

**Comment by JensTimmerman** [comment]
@StyXman it is used by whomever runs `python setup.py bdist_rpm` to generate an rpm.
At the moment that would only be internal use at our team.

**Comment by StyXman** [comment]
It's in. Thanks @JensTimmerman !

**Pull request merged**
